import { CRICKETER_PORTRAIT_SEEDS } from "./cricket-portraits";

export type CricketRole =
  | "BATTER"
  | "FAST_BOWLER"
  | "SPIN_BOWLER"
  | "ALL_ROUNDER"
  | "WICKETKEEPER";

export interface CricketPlayerItem {
  id: string;
  title: string; // Player Name
  year: number; // Age
  genre: string; // Role name (e.g. "Top-Order Batter")
  genres: string[]; // ["Batter", "Captain", "India"]
  basePrice: number; // in Crores (e.g. 2, 1.5, 1)
  posterPosition?: string;
  imdbRating: number; // Player Power Rating / Impact (e.g. 9.4)
  boxOffice: number; // Career T20 Runs or Wickets index
  director: string; // Country / Nationality
  studio?: string; // Player Specialization / Specialty Tag (NO franchise team name!)
  category: "BATTERS" | "FAST_BOWLERS" | "SPINNERS" | "ALL_ROUNDERS" | "WICKETKEEPERS" | "ALL";
  tagline?: string;
  photoUrl: string;
  role: CricketRole;
  country: string;
  countryFlag: string;
  stats: {
    matches: number;
    runs?: number;
    wickets?: number;
    strikeRate?: number;
    economy?: number;
    highestScore?: string;
    bestBowling?: string;
    fifties?: number;
  };
  signatureSkill: string;
}

/** Maximum foreign/overseas players a franchise can purchase into their 12–18 player squad */
export const MAX_OVERSEAS_PER_SQUAD = 7;

/** Maximum foreign/overseas players allowed in the final Playing 11 match lineup */
export const MAX_OVERSEAS_IN_PLAYING_11 = 4;

/**
 * Returns true if player is an overseas / foreign player (non-Indian).
 */
export function isOverseasPlayer(
  player: { country?: string; director?: string } | null | undefined,
): boolean {
  if (!player) return false;
  const c = (player.country || player.director || "").trim().toLowerCase();
  return c !== "india" && c !== "indian" && c !== "🇮🇳" && c.length > 0;
}

export const cricketPlayers: CricketPlayerItem[] = [
  // ==========================================
  // --- MARQUEE BATTERS (INDIAN & OVERSEAS) ---
  // ==========================================
  {
    id: "virat-kohli",
    title: "Virat Kohli",
    year: 36,
    genre: "Top-Order Batter",
    genres: ["Batter", "Anchor", "Chase Master"],
    basePrice: 2,
    imdbRating: 9.9,
    boxOffice: 12850,
    director: "India",
    studio: "Elite Chase Master & Century Machine",
    category: "BATTERS",
    tagline: "All-time highest run scorer with unmatched chasing mastery",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["virat-kohli"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 252, runs: 8004, strikeRate: 131.97, highestScore: "113*", fifties: 55 },
    signatureSkill: "Classic Cover Drive & Death-Over Acceleration",
  },
  {
    id: "rohit-sharma",
    title: "Rohit Sharma",
    year: 37,
    genre: "Opening Batter",
    genres: ["Batter", "Opener", "Six Hitter"],
    basePrice: 2,
    imdbRating: 9.7,
    boxOffice: 11500,
    director: "India",
    studio: "The Hitman & Powerplay Demolisher",
    category: "BATTERS",
    tagline: "Record 5-time championship captain and effortless six-hitter",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["rohit-sharma"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 257, runs: 6628, strikeRate: 131.14, highestScore: "109*", fifties: 43 },
    signatureSkill: "Effortless Pull Shot & Powerplay Mayhem",
  },
  {
    id: "suryakumar-yadav",
    title: "Suryakumar Yadav",
    year: 34,
    genre: "360° Middle-Order Batter",
    genres: ["Batter", "360-Degree", "Innovator"],
    basePrice: 2,
    imdbRating: 9.8,
    boxOffice: 7800,
    director: "India",
    studio: "World No. 1 T20 Dynamic Maestro",
    category: "BATTERS",
    tagline: "Unstoppable 360-degree stroke maker who manipulates any field",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["suryakumar-yadav"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 150, runs: 3594, strikeRate: 145.32, highestScore: "103*", fifties: 24 },
    signatureSkill: "Suplex Scoop & Behind-Square Ramp",
  },
  {
    id: "travis-head",
    title: "Travis Head",
    year: 31,
    genre: "Explosive Opener",
    genres: ["Batter", "Ultra-Aggressive", "Powerplay Specialist"],
    basePrice: 2,
    imdbRating: 9.6,
    boxOffice: 4200,
    director: "Australia",
    studio: "High-Octane Powerplay Destruction",
    category: "BATTERS",
    tagline: "Fearless left-handed juggernaut who dismantles bowling attacks inside 6 overs",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["travis-head"] || "",
    role: "BATTER",
    country: "Australia",
    countryFlag: "🇦🇺",
    stats: { matches: 43, runs: 1045, strikeRate: 167.8, highestScore: "102", fifties: 6 },
    signatureSkill: "Flaming Square Cuts & Lofted Off-Drives",
  },
  {
    id: "shubman-gill",
    title: "Shubman Gill",
    year: 25,
    genre: "Classical Top-Order Batter",
    genres: ["Batter", "Anchor", "Future Leader"],
    basePrice: 2,
    imdbRating: 9.4,
    boxOffice: 4800,
    director: "India",
    studio: "Orange Cap Phenomenon & Pure Technique",
    category: "BATTERS",
    tagline: "Elegant stroke player with supreme timing and monster conversion rates",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["shubman-gill"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 103, runs: 3216, strikeRate: 135.7, highestScore: "129", fifties: 20 },
    signatureSkill: "Short-Arm Jab & Pristine Cover Punch",
  },
  {
    id: "yashasvi-jaiswal",
    title: "Yashasvi Jaiswal",
    year: 23,
    genre: "Dynamic Left-Hand Opener",
    genres: ["Batter", "Opener", "Gen-Z Sensation"],
    basePrice: 2,
    imdbRating: 9.5,
    boxOffice: 3600,
    director: "India",
    studio: "Fastest 50 Record Holder (13 Balls)",
    category: "BATTERS",
    tagline: "Fearless young dynamo who strikes from ball one without hesitation",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["yashasvi-jaiswal"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 52, runs: 1607, strikeRate: 150.6, highestScore: "124", fifties: 9 },
    signatureSkill: "First-Ball Boundary Launch & Uppercut",
  },
  {
    id: "rinku-singh",
    title: "Rinku Singh",
    year: 27,
    genre: "Clutch Death-Overs Finisher",
    genres: ["Batter", "Finisher", "Clutch Specialist"],
    basePrice: 1.5,
    imdbRating: 9.3,
    boxOffice: 2400,
    director: "India",
    studio: "5 Consecutive Sixes Miracle Finisher",
    category: "BATTERS",
    tagline: "Cold-blooded finisher renowned for turning impossible chases into triumphs",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["rinku-singh"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 45, runs: 893, strikeRate: 143.3, highestScore: "67*", fifties: 4 },
    signatureSkill: "Last-Over Slog Sweep & Straight Sixes",
  },
  {
    id: "ruturaj-gaikwad",
    title: "Ruturaj Gaikwad",
    year: 28,
    genre: "Elegant Opening Batter & Captain",
    genres: ["Batter", "Opener", "Orange Cap Winner"],
    basePrice: 2,
    imdbRating: 9.4,
    boxOffice: 4200,
    director: "India",
    studio: "Flawless Technique & Spin Dominator",
    category: "BATTERS",
    tagline: "Pristine stroke-maker who transitions seamlessly from anchor to ultra-accelerator",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["ruturaj-gaikwad"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 66, runs: 2380, strikeRate: 136.9, highestScore: "108*", fifties: 18 },
    signatureSkill: "Inside-Out Loft & Back-Foot Punch",
  },
  {
    id: "tilak-varma",
    title: "Tilak Varma",
    year: 22,
    genre: "Versatile Left-Hand Batter",
    genres: ["Batter", "Middle-Order", "Clutch"],
    basePrice: 1.5,
    imdbRating: 9.2,
    boxOffice: 2200,
    director: "India",
    studio: "Back-to-Back T20I Century Prodigy",
    category: "BATTERS",
    tagline: "Ultra-composed young left-hander capable of anchoring or blasting at 200+ SR",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["tilak-varma"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 38, runs: 1156, strikeRate: 146.3, highestScore: "84*", fifties: 6 },
    signatureSkill: "Deep Square-Leg Flick & Lofted Extra-Cover Drive",
  },
  {
    id: "abhishek-sharma",
    title: "Abhishek Sharma",
    year: 24,
    genre: "Blazing Powerplay Opener",
    genres: ["Batter", "Opener", "Spin All-Rounder"],
    basePrice: 2,
    imdbRating: 9.3,
    boxOffice: 2800,
    director: "India",
    studio: "Fastest Indian T20 Century Blitz",
    category: "BATTERS",
    tagline: "All-out attack opening batter with unmatched intent against raw pace and spin",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["abhishek-sharma"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 63, runs: 1377, strikeRate: 155.1, highestScore: "100", fifties: 7 },
    signatureSkill: "No-Look Pull Shot & Stand-and-Deliver Maximums",
  },
  {
    id: "sai-sudharsan",
    title: "Sai Sudharsan",
    year: 23,
    genre: "Technique-Rich Top-Order Anchor",
    genres: ["Batter", "Top-Order", "Anchor"],
    basePrice: 1.5,
    imdbRating: 9.1,
    boxOffice: 1900,
    director: "India",
    studio: "Big-Match Final 96 Runs Masterclass",
    category: "BATTERS",
    tagline: "Classical high-average left-hander with impenetrable orthodox fundamentals",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["sai-sudharsan"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 25, runs: 1034, strikeRate: 139.2, highestScore: "103", fifties: 6 },
    signatureSkill: "Exquisite On-Drive & Late Cut",
  },
  {
    id: "shreyas-iyer",
    title: "Shreyas Iyer",
    year: 30,
    genre: "Middle-Order Anchor & Title Captain",
    genres: ["Batter", "Captain", "Spin Dominator"],
    basePrice: 2,
    imdbRating: 9.4,
    boxOffice: 4600,
    director: "India",
    studio: "Championship Winning Franchise Leader",
    category: "BATTERS",
    tagline: "Exceptional leader and arguably the most destructive player of spin bowling",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["shreyas-iyer"] || "",
    role: "BATTER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 115, runs: 3127, strikeRate: 127.5, highestScore: "96", fifties: 21 },
    signatureSkill: "Stepping Out Loft Over Long-On Against Spin",
  },
  {
    id: "david-miller",
    title: "David Miller",
    year: 35,
    genre: "Middle-Order Power Finisher",
    genres: ["Batter", "Finisher", "Killer Miller"],
    basePrice: 1.5,
    imdbRating: 9.1,
    boxOffice: 4200,
    director: "South Africa",
    studio: "Killer Miller Ice-Cold Finisher",
    category: "BATTERS",
    tagline: "Calm under pressure with brutal six-hitting power against pace and spin",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["david-miller"] || "",
    role: "BATTER",
    country: "South Africa",
    countryFlag: "🇿🇦",
    stats: { matches: 130, runs: 2924, strikeRate: 139.2, highestScore: "101*", fifties: 13 },
    signatureSkill: "Flat-Batted Monster Pulls Over Mid-Wicket",
  },
  {
    id: "faf-du-plessis",
    title: "Faf du Plessis",
    year: 40,
    genre: "Veteran Captain & Power Opener",
    genres: ["Batter", "Captain", "Fitness Icon"],
    basePrice: 2,
    imdbRating: 9.3,
    boxOffice: 5400,
    director: "South Africa",
    studio: "Consistent 700+ Run Season Anchor",
    category: "BATTERS",
    tagline: "Unbelievable athletic stamina, supreme ramp shots, and inspirational leadership",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["faf-du-plessis"] || "",
    role: "BATTER",
    country: "South Africa",
    countryFlag: "🇿🇦",
    stats: { matches: 145, runs: 4571, strikeRate: 136.4, highestScore: "96", fifties: 37 },
    signatureSkill: "Ramp Over Keeper & Stepped-Out Cover Loft",
  },
  {
    id: "david-warner",
    title: "David Warner",
    year: 38,
    genre: "3-Time Orange Cap Legendary Opener",
    genres: ["Batter", "Opener", "Title Captain"],
    basePrice: 2,
    imdbRating: 9.6,
    boxOffice: 8200,
    director: "Australia",
    studio: "All-Time Greatest Overseas Batter (6500+ Runs)",
    category: "BATTERS",
    tagline: "Relentless aggressive opener with the highest number of 50+ scores in tournament history",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["david-warner"] || "",
    role: "BATTER",
    country: "Australia",
    countryFlag: "🇦🇺",
    stats: { matches: 184, runs: 6565, strikeRate: 139.8, highestScore: "126", fifties: 62 },
    signatureSkill: "Switch-Hit Six & Rapid Boundary Running",
  },

  // ===============================================
  // --- WICKETKEEPER-BATTERS (INDIAN & OVERSEAS) ---
  // ===============================================
  {
    id: "ms-dhoni",
    title: "MS Dhoni",
    year: 43,
    genre: "Legendary Keeper & Master Tactician",
    genres: ["Wicketkeeper", "Captain Cool", "Master Tactician"],
    basePrice: 2,
    imdbRating: 10.0,
    boxOffice: 5240,
    director: "India",
    studio: "5-Time Title Winning Captain Cool & Finisher",
    category: "WICKETKEEPERS",
    tagline: "Fastest stumping hands in history (0.08s) and the greatest tactical mind",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["ms-dhoni"] || "",
    role: "WICKETKEEPER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 264, runs: 5243, strikeRate: 137.5, highestScore: "84*", fifties: 24 },
    signatureSkill: "Lightning 0.08s Stumping & Helicopter Finisher",
  },
  {
    id: "heinrich-klaasen",
    title: "Heinrich Klaasen",
    year: 33,
    genre: "Premier Wicketkeeper-Batter",
    genres: ["Wicketkeeper", "Spin Smasher", "Power Hitter"],
    basePrice: 2,
    imdbRating: 9.8,
    boxOffice: 4100,
    director: "South Africa",
    studio: "Most Feared Spin Destroyer in World Cricket",
    category: "WICKETKEEPERS",
    tagline: "Unreal strike rate against spin (185+) and towering back-foot pull shots",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["heinrich-klaasen"] || "",
    role: "WICKETKEEPER",
    country: "South Africa",
    countryFlag: "🇿🇦",
    stats: { matches: 35, runs: 993, strikeRate: 168.3, highestScore: "104", fifties: 6 },
    signatureSkill: "Monster Back-Foot Pull Over Deep Mid-Wicket",
  },
  {
    id: "rishabh-pant",
    title: "Rishabh Pant",
    year: 27,
    genre: "Dynamic Left-Hand Wicketkeeper",
    genres: ["Wicketkeeper", "Audacious Stroke-Maker", "Captain"],
    basePrice: 2,
    imdbRating: 9.6,
    boxOffice: 3400,
    director: "India",
    studio: "Record Auction Superstar & Miracle Comeback",
    category: "WICKETKEEPERS",
    tagline: "Audacious one-handed sixes and unmatched energy behind the stumps",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["rishabh-pant"] || "",
    role: "WICKETKEEPER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 111, runs: 3284, strikeRate: 148.9, highestScore: "128*", fifties: 18 },
    signatureSkill: "One-Handed 95-Meter Hook Shot",
  },
  {
    id: "jos-buttler",
    title: "Jos Buttler",
    year: 34,
    genre: "Elite Opener & Wicketkeeper",
    genres: ["Wicketkeeper", "Opener", "Century Hunter"],
    basePrice: 2,
    imdbRating: 9.7,
    boxOffice: 4200,
    director: "England",
    studio: "Orange Cap Legend (863 Runs in a Single Season)",
    category: "WICKETKEEPERS",
    tagline: "Holds record for 7 dynamic centuries in franchise history",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["jos-buttler"] || "",
    role: "WICKETKEEPER",
    country: "England",
    countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    stats: { matches: 107, runs: 3582, strikeRate: 147.5, highestScore: "124", fifties: 19 },
    signatureSkill: "Ramp Over Fine Leg & Thunderous Straight Loft",
  },
  {
    id: "nicholas-pooran",
    title: "Nicholas Pooran",
    year: 29,
    genre: "Left-Hand Power Hitter & Keeper",
    genres: ["Wicketkeeper", "Power Hitter", "Clean Striker"],
    basePrice: 2,
    imdbRating: 9.5,
    boxOffice: 3600,
    director: "West Indies",
    studio: "Cleanest Six-Hitting Swing in Global T20s",
    category: "WICKETKEEPERS",
    tagline: "Pure bat swing producing effortless maximums to all parts of the ground",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["nicholas-pooran"] || "",
    role: "WICKETKEEPER",
    country: "West Indies",
    countryFlag: "🌴",
    stats: { matches: 76, runs: 1769, strikeRate: 162.3, highestScore: "77", fifties: 9 },
    signatureSkill: "High Back-Lift Slog Sweep Over Deep Square Leg",
  },
  {
    id: "sanju-samson",
    title: "Sanju Samson",
    year: 30,
    genre: "Top-Order Keeper & Aggressive Captain",
    genres: ["Wicketkeeper", "Captain", "Flamboyant Hitter"],
    basePrice: 2,
    imdbRating: 9.4,
    boxOffice: 4400,
    director: "India",
    studio: "Consecutive T20I Century Record Holder",
    category: "WICKETKEEPERS",
    tagline: "Aesthetic stroke play and immense back-foot authority against 150 km/h pacers",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["sanju-samson"] || "",
    role: "WICKETKEEPER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 167, runs: 4419, strikeRate: 138.9, highestScore: "119", fifties: 25 },
    signatureSkill: "Stand-Tall Inside-Out Loft Over Extra Cover",
  },
  {
    id: "kl-rahul",
    title: "KL Rahul",
    year: 32,
    genre: "Anchor Batter & Wicketkeeper",
    genres: ["Wicketkeeper", "Anchor", "Orange Cap Winner"],
    basePrice: 2,
    imdbRating: 9.3,
    boxOffice: 4700,
    director: "India",
    studio: "Consistent 500+ Run Season Anchor",
    category: "WICKETKEEPERS",
    tagline: "Silky smooth orthodox technique with 4 franchise centuries",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["kl-rahul"] || "",
    role: "WICKETKEEPER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 132, runs: 4683, strikeRate: 134.6, highestScore: "132*", fifties: 37 },
    signatureSkill: "Wristy Flick Over Deep Mid-Wicket",
  },
  {
    id: "phil-salt",
    title: "Phil Salt",
    year: 28,
    genre: "Explosive Wicketkeeper-Opener",
    genres: ["Wicketkeeper", "Opener", "All-Out Attack"],
    basePrice: 1.5,
    imdbRating: 9.2,
    boxOffice: 2100,
    director: "England",
    studio: "Aggressive Powerplay Blitz Champion",
    category: "WICKETKEEPERS",
    tagline: "Strikes with 180+ strike rate in the first 6 overs to establish dominant totals",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["phil-salt"] || "",
    role: "WICKETKEEPER",
    country: "England",
    countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    stats: { matches: 21, runs: 653, strikeRate: 175.5, highestScore: "89*", fifties: 6 },
    signatureSkill: "Brutal Powerplay Cut & Lofted Drive",
  },
  {
    id: "ishan-kishan",
    title: "Ishan Kishan",
    year: 26,
    genre: "Pocket Dynamo Keeper-Opener",
    genres: ["Wicketkeeper", "Opener", "Power Hitter"],
    basePrice: 2,
    imdbRating: 9.2,
    boxOffice: 3100,
    director: "India",
    studio: "Double Century International Record Holder",
    category: "WICKETKEEPERS",
    tagline: "Explosive left-hander capable of clearing any ground with rapid bat swing",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["ishan-kishan"] || "",
    role: "WICKETKEEPER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 105, runs: 2644, strikeRate: 135.8, highestScore: "99", fifties: 16 },
    signatureSkill: "Aerial Pull Shot Over Deep Mid-Wicket",
  },
  {
    id: "quinton-de-kock",
    title: "Quinton de Kock",
    year: 32,
    genre: "World-Class Keeper & Opener",
    genres: ["Wicketkeeper", "Opener", "Champion"],
    basePrice: 2,
    imdbRating: 9.4,
    boxOffice: 4200,
    director: "South Africa",
    studio: "140* Highest Individual Opening Partnership",
    category: "WICKETKEEPERS",
    tagline: "Crisp timing on the off-side and reliable acrobatic glovework",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["quinton-de-kock"] || "",
    role: "WICKETKEEPER",
    country: "South Africa",
    countryFlag: "🇿🇦",
    stats: { matches: 107, runs: 3157, strikeRate: 134.2, highestScore: "140*", fifties: 23 },
    signatureSkill: "Pick-Up Whip Over Square Leg & Square Cut",
  },
  {
    id: "dhruv-jurel",
    title: "Dhruv Jurel",
    year: 24,
    genre: "Composed Middle-Order Keeper",
    genres: ["Wicketkeeper", "Finisher", "Impact Player"],
    basePrice: 1.5,
    imdbRating: 9.0,
    boxOffice: 1400,
    director: "India",
    studio: "Clutch Pressure Handler & Gloveman",
    category: "WICKETKEEPERS",
    tagline: "Smart strike rotator with crisp power hitting against 145+ km/h pace",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["dhruv-jurel"] || "",
    role: "WICKETKEEPER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 28, runs: 347, strikeRate: 151.5, highestScore: "52*", fifties: 2 },
    signatureSkill: "Inside-Out Lofted Slice & Slower Ball Ramp",
  },

  // ============================================
  // --- FAST BOWLING (INDIAN & OVERSEAS) ---
  // ============================================
  {
    id: "jasprit-bumrah",
    title: "Jasprit Bumrah",
    year: 31,
    genre: "Premier Strike & Death Bowler",
    genres: ["Bowler", "Fast Bowler", "Yorker King"],
    basePrice: 2,
    imdbRating: 10.0,
    boxOffice: 165,
    director: "India",
    studio: "The World's Deadliest Death-Overs Weapon",
    category: "FAST_BOWLERS",
    tagline: "Pinpoint toe-crushing yorkers, lethal bouncers, and impossible economy",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["jasprit-bumrah"] || "",
    role: "FAST_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 133, wickets: 165, economy: 7.3, bestBowling: "5/10" },
    signatureSkill: "145 km/h Laser-Guided Toe Crusher",
  },
  {
    id: "pat-cummins",
    title: "Pat Cummins",
    year: 31,
    genre: "Pace Bowler & World Champion Captain",
    genres: ["Bowler", "Fast Bowler", "Captain", "All-Rounder"],
    basePrice: 2,
    imdbRating: 9.7,
    boxOffice: 75,
    director: "Australia",
    studio: "World Cup Winning Captain & Fast Bowler",
    category: "FAST_BOWLERS",
    tagline: "High-pace heavy ball specialist with lethal lower-order blitz capabilities",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["pat-cummins"] || "",
    role: "FAST_BOWLER",
    country: "Australia",
    countryFlag: "🇦🇺",
    stats: { matches: 58, wickets: 63, economy: 8.7, strikeRate: 152.4, bestBowling: "4/34" },
    signatureSkill: "Hard-Length Seam & 14-Ball Fifty Power",
  },
  {
    id: "mitchell-starc",
    title: "Mitchell Starc",
    year: 35,
    genre: "Left-Arm Express Pacer",
    genres: ["Bowler", "Fast Bowler", "Left-Arm Pacer"],
    basePrice: 2,
    imdbRating: 9.6,
    boxOffice: 65,
    director: "Australia",
    studio: "Big-Match Clutch Final Wrecker",
    category: "FAST_BOWLERS",
    tagline: "Deadly swing upfront and swinging inswinging yorkers at high velocity",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["mitchell-starc"] || "",
    role: "FAST_BOWLER",
    country: "Australia",
    countryFlag: "🇦🇺",
    stats: { matches: 41, wickets: 51, economy: 8.6, bestBowling: "4/15" },
    signatureSkill: "150 km/h Inswinging Stump Shatterer",
  },
  {
    id: "trent-boult",
    title: "Trent Boult",
    year: 35,
    genre: "Left-Arm Powerplay Swing King",
    genres: ["Bowler", "Fast Bowler", "Powerplay Specialist"],
    basePrice: 2,
    imdbRating: 9.5,
    boxOffice: 121,
    director: "New Zealand",
    studio: "First-Over Wicket Guarantee",
    category: "FAST_BOWLERS",
    tagline: "Supreme banana inswing against right-handers with over 50 first-over wickets",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["trent-boult"] || "",
    role: "FAST_BOWLER",
    country: "New Zealand",
    countryFlag: "🇳🇿",
    stats: { matches: 104, wickets: 121, economy: 8.2, bestBowling: "4/18" },
    signatureSkill: "Devastating First-Over Inswinger",
  },
  {
    id: "kagiso-rabada",
    title: "Kagiso Rabada",
    year: 29,
    genre: "Express Pace & Strike Machine",
    genres: ["Bowler", "Fast Bowler", "Express Pace"],
    basePrice: 2,
    imdbRating: 9.4,
    boxOffice: 117,
    director: "South Africa",
    studio: "Purple Cap Express Fast Bowler",
    category: "FAST_BOWLERS",
    tagline: "Fierce pace, steep bounce, and clinical execution in Super Overs",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["kagiso-rabada"] || "",
    role: "FAST_BOWLER",
    country: "South Africa",
    countryFlag: "🇿🇦",
    stats: { matches: 80, wickets: 117, economy: 8.4, bestBowling: "4/21" },
    signatureSkill: "148 km/h Throat Bouncer & Searing Yorker",
  },
  {
    id: "mohammed-shami",
    title: "Mohammed Shami",
    year: 34,
    genre: "Upright Seam & Powerplay Maestro",
    genres: ["Bowler", "Fast Bowler", "Seam Wizard"],
    basePrice: 2,
    imdbRating: 9.5,
    boxOffice: 127,
    director: "India",
    studio: "Purple Cap Seam Presentation Master",
    category: "FAST_BOWLERS",
    tagline: "World's most immaculate upright seam position creating devastating lateral movement",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["mohammed-shami"] || "",
    role: "FAST_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 110, wickets: 127, economy: 8.4, bestBowling: "4/11" },
    signatureSkill: "Immaculate Upright Seam & Top-of-Off Nipper",
  },
  {
    id: "mohammed-siraj",
    title: "Mohammed Siraj",
    year: 31,
    genre: "High-Energy Powerplay Pacer",
    genres: ["Bowler", "Fast Bowler", "Outswing Specialist"],
    basePrice: 2,
    imdbRating: 9.3,
    boxOffice: 93,
    director: "India",
    studio: "Fiery Fast-Bowling Strike Force",
    category: "FAST_BOWLERS",
    tagline: "Relentless aggressive pace and shape with the new white kookaburra ball",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["mohammed-siraj"] || "",
    role: "FAST_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 93, wickets: 93, economy: 8.6, bestBowling: "4/21" },
    signatureSkill: "145 km/h Late Outswinger & Wobble Seam",
  },
  {
    id: "arshdeep-singh",
    title: "Arshdeep Singh",
    year: 26,
    genre: "Left-Arm Death-Overs Specialist",
    genres: ["Bowler", "Fast Bowler", "Death Bowler"],
    basePrice: 2,
    imdbRating: 9.3,
    boxOffice: 76,
    director: "India",
    studio: "T20 World Cup Leading Wicket-Taker",
    category: "FAST_BOWLERS",
    tagline: "Master of wide yorkers and deceptive knuckle-balls in high-pressure 20th overs",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["arshdeep-singh"] || "",
    role: "FAST_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 65, wickets: 76, economy: 8.7, bestBowling: "5/32" },
    signatureSkill: "Pinpoint Wide-Line Yorker & Slower Ball",
  },
  {
    id: "matheesha-pathirana",
    title: "Matheesha Pathirana",
    year: 22,
    genre: "Sling-Action Death Specialist",
    genres: ["Bowler", "Fast Bowler", "Slinger"],
    basePrice: 1.5,
    imdbRating: 9.2,
    boxOffice: 34,
    director: "Sri Lanka",
    studio: "Baby Malinga Sling Action Wonder",
    category: "FAST_BOWLERS",
    tagline: "Unorthodox low-arm release hurling 150 km/h rockets right into the blockhole",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["matheesha-pathirana"] || "",
    role: "FAST_BOWLER",
    country: "Sri Lanka",
    countryFlag: "🇱🇰",
    stats: { matches: 20, wickets: 34, economy: 7.8, bestBowling: "4/28" },
    signatureSkill: "Ultra-Low Angle 150 km/h Dipper",
  },
  {
    id: "bhuvneshwar-kumar",
    title: "Bhuvneshwar Kumar",
    year: 35,
    genre: "Two-Time Purple Cap Swing King",
    genres: ["Bowler", "Fast Bowler", "Swing Wizard"],
    basePrice: 2,
    imdbRating: 9.3,
    boxOffice: 181,
    director: "India",
    studio: "Record 2-Time Purple Cap Winner (181 Wickets)",
    category: "FAST_BOWLERS",
    tagline: "Legendary precision swing both ways and economical death-over knuckle balls",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["bhuvneshwar-kumar"] || "",
    role: "FAST_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 176, wickets: 181, economy: 7.5, bestBowling: "5/19" },
    signatureSkill: "Two-Way Swing & Knuckle-Ball Yorker",
  },
  {
    id: "harshit-rana",
    title: "Harshit Rana",
    year: 23,
    genre: "Hard-Length Heavy Ball Pacer",
    genres: ["Bowler", "Fast Bowler", "Aggressive"],
    basePrice: 1.5,
    imdbRating: 9.0,
    boxOffice: 25,
    director: "India",
    studio: "Title-Winning Death Overs Champion",
    category: "FAST_BOWLERS",
    tagline: "Steep bounce from a high release with disguised back-of-the-hand slower balls",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["harshit-rana"] || "",
    role: "FAST_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 21, wickets: 25, economy: 8.9, bestBowling: "3/24" },
    signatureSkill: "Heavy Bouncer & Back-of-Hand Slower Delivery",
  },
  {
    id: "mayank-yadav",
    title: "Mayank Yadav",
    year: 22,
    genre: "156.7 km/h Express Thunderbolt",
    genres: ["Bowler", "Fast Bowler", "Fastest Delivery"],
    basePrice: 1.5,
    imdbRating: 9.1,
    boxOffice: 15,
    director: "India",
    studio: "Raw 156+ km/h Velocity Phenom",
    category: "FAST_BOWLERS",
    tagline: "Breathtaking raw pace hurrying world-class batters off a short runup",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["mayank-yadav"] || "",
    role: "FAST_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 4, wickets: 7, economy: 6.9, bestBowling: "3/14" },
    signatureSkill: "156.7 km/h Rib-Cage Snorter",
  },
  {
    id: "josh-hazlewood",
    title: "Josh Hazlewood",
    year: 34,
    genre: "Metronomic Accuracy Fast Bowler",
    genres: ["Bowler", "Fast Bowler", "Test Match Lengths"],
    basePrice: 2,
    imdbRating: 9.4,
    boxOffice: 35,
    director: "Australia",
    studio: "Test Match Discipline in T20 Powerplay",
    category: "FAST_BOWLERS",
    tagline: "Laser-focused fifth stump line and deceptive extra bounce",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["josh-hazlewood"] || "",
    role: "FAST_BOWLER",
    country: "Australia",
    countryFlag: "🇦🇺",
    stats: { matches: 27, wickets: 35, economy: 8.0, bestBowling: "4/25" },
    signatureSkill: "Relentless Top-of-Off Seam Movement",
  },
  {
    id: "lockie-ferguson",
    title: "Lockie Ferguson",
    year: 33,
    genre: "Express 150 km/h Enforcer",
    genres: ["Bowler", "Fast Bowler", "Speedster"],
    basePrice: 1.5,
    imdbRating: 9.1,
    boxOffice: 46,
    director: "New Zealand",
    studio: "Hat-Trick Maiden Over Specialist",
    category: "FAST_BOWLERS",
    tagline: "Searing heat combined with an unreadable dipping slower yorker",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["lockie-ferguson"] || "",
    role: "FAST_BOWLER",
    country: "New Zealand",
    countryFlag: "🇳🇿",
    stats: { matches: 45, wickets: 46, economy: 8.7, bestBowling: "4/28" },
    signatureSkill: "152 km/h Fast Bouncer & 120 km/h Knuckle Dipper",
  },

  // ==========================================
  // --- ALL-ROUNDERS (INDIAN & OVERSEAS) ---
  // ==========================================
  {
    id: "hardik-pandya",
    title: "Hardik Pandya",
    year: 31,
    genre: "Fast-Bowling All-Rounder & Captain",
    genres: ["All-Rounder", "Fast Bowler", "Finisher", "Captain"],
    basePrice: 2,
    imdbRating: 9.7,
    boxOffice: 4800,
    director: "India",
    studio: "Clutch World Cup Final Hero & Power Finisher",
    category: "ALL_ROUNDERS",
    tagline: "Rare 140 km/h bowling asset and destructive middle-order power hitter",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["hardik-pandya"] || "",
    role: "ALL_ROUNDER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 137, runs: 2525, wickets: 64, strikeRate: 145.8, highestScore: "91" },
    signatureSkill: "Helicopter Whack & Hard-Length Seam",
  },
  {
    id: "andre-russell",
    title: "Andre Russell",
    year: 36,
    genre: "Explosive Power All-Rounder",
    genres: ["All-Rounder", "Power Hitter", "Death Bowler"],
    basePrice: 2,
    imdbRating: 9.8,
    boxOffice: 4600,
    director: "West Indies",
    studio: "Highest Career Strike Rate in T20 History (174.9)",
    category: "ALL_ROUNDERS",
    tagline: "Muscle Russell: capable of chasing 60 runs off 3 overs with raw power",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["andre-russell"] || "",
    role: "ALL_ROUNDER",
    country: "West Indies",
    countryFlag: "🌴",
    stats: { matches: 127, runs: 2484, wickets: 115, strikeRate: 174.9, highestScore: "88*" },
    signatureSkill: "115-Meter Stadium Cleared Monster Sixes",
  },
  {
    id: "sunil-narine",
    title: "Sunil Narine",
    year: 36,
    genre: "Mystery Spinner & Pinch Hitter",
    genres: ["All-Rounder", "Mystery Spinner", "Pinch Hitter"],
    basePrice: 2,
    imdbRating: 9.9,
    boxOffice: 3800,
    director: "West Indies",
    studio: "3-Time MVP & Dual Threat Sensation",
    category: "ALL_ROUNDERS",
    tagline: "Virtually unhittable economy rate paired with explosive opening batting blitzes",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["sunil-narine"] || "",
    role: "ALL_ROUNDER",
    country: "West Indies",
    countryFlag: "🌴",
    stats: { matches: 177, runs: 1534, wickets: 180, economy: 6.7, strikeRate: 165.8, highestScore: "109" },
    signatureSkill: "Knuckle Ball Carrom Spin & Powerplay Blitz",
  },
  {
    id: "ravindra-jadeja",
    title: "Ravindra Jadeja",
    year: 36,
    genre: "3D Champion All-Rounder",
    genres: ["All-Rounder", "Left-Arm Spinner", "Gun Fielder"],
    basePrice: 2,
    imdbRating: 9.6,
    boxOffice: 4100,
    director: "India",
    studio: "Sir Jadeja: Final Ball Title Winner & Gun Fielder",
    category: "ALL_ROUNDERS",
    tagline: "Laser-accurate flat spin, bullet throwing arm, and last-over match-winning strikes",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["ravindra-jadeja"] || "",
    role: "ALL_ROUNDER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 240, runs: 2959, wickets: 160, economy: 7.6, strikeRate: 129.8, highestScore: "62*" },
    signatureSkill: "Rapid Fire Overs & Direct-Hit Run Outs",
  },
  {
    id: "glenn-maxwell",
    title: "Glenn Maxwell",
    year: 36,
    genre: "The Big Show All-Rounder",
    genres: ["All-Rounder", "Off-Spinner", "Unorthodox Hitter"],
    basePrice: 2,
    imdbRating: 9.4,
    boxOffice: 4700,
    director: "Australia",
    studio: "The Big Show Reverse-Sweep Specialist",
    category: "ALL_ROUNDERS",
    tagline: "Inventive switch-hits and crucial middle-overs off-spin wickets",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["glenn-maxwell"] || "",
    role: "ALL_ROUNDER",
    country: "Australia",
    countryFlag: "🇦🇺",
    stats: { matches: 134, runs: 2771, wickets: 37, strikeRate: 156.7, highestScore: "95" },
    signatureSkill: "Switch-Hit Six Over Third Man",
  },
  {
    id: "axar-patel",
    title: "Axar Patel",
    year: 31,
    genre: "Clutch Left-Arm All-Rounder",
    genres: ["All-Rounder", "Left-Arm Spinner", "Middle-Order Anchor"],
    basePrice: 1.5,
    imdbRating: 9.3,
    boxOffice: 2900,
    director: "India",
    studio: "T20 World Cup Final Crisis Man",
    category: "ALL_ROUNDERS",
    tagline: "Rock-solid middle order rescue batter with parsimonious left-arm darts",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["axar-patel"] || "",
    role: "ALL_ROUNDER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 150, runs: 1653, wickets: 123, economy: 7.2, strikeRate: 130.8 },
    signatureSkill: "Straight Arm-Ball & Clean Lofted Drives",
  },
  {
    id: "marcus-stoinis",
    title: "Marcus Stoinis",
    year: 35,
    genre: "Power All-Rounder & Match Winner",
    genres: ["All-Rounder", "Medium Pacer", "Power Hitter"],
    basePrice: 1.5,
    imdbRating: 9.1,
    boxOffice: 3100,
    director: "Australia",
    studio: "Big-Hitting Muscle Finisher & Century Hero",
    category: "ALL_ROUNDERS",
    tagline: "Aggressive stroke maker who clears massive boundaries with ease",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["marcus-stoinis"] || "",
    role: "ALL_ROUNDER",
    country: "Australia",
    countryFlag: "🇦🇺",
    stats: { matches: 96, runs: 1866, wickets: 43, strikeRate: 142.1, highestScore: "124*" },
    signatureSkill: "Brutal Flat-Batted Hits & Heavy Cut",
  },
  {
    id: "shivam-dube",
    title: "Shivam Dube",
    year: 31,
    genre: "Middle-Overs Spin Enforcer",
    genres: ["All-Rounder", "Spin Destroyer", "Medium Pacer"],
    basePrice: 1.5,
    imdbRating: 9.0,
    boxOffice: 2200,
    director: "India",
    studio: "Long-Levers Spin Executioner",
    category: "ALL_ROUNDERS",
    tagline: "Destroys spinners with gigantic arcs over long-on without moving footwork",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["shivam-dube"] || "",
    role: "ALL_ROUNDER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 65, runs: 1502, strikeRate: 159.2, highestScore: "95*", fifties: 9 },
    signatureSkill: "Stand-and-Deliver 105m Straight Launch",
  },
  {
    id: "washington-sundar",
    title: "Washington Sundar",
    year: 25,
    genre: "Powerplay Off-Spin All-Rounder",
    genres: ["All-Rounder", "Off-Spinner", "Top-Order Capable"],
    basePrice: 1.5,
    imdbRating: 9.0,
    boxOffice: 1800,
    director: "India",
    studio: "Powerplay Stifler & Graceful Left-Hander",
    category: "ALL_ROUNDERS",
    tagline: "Tidy economy bowling inside the first 6 overs and elegant batting style",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["washington-sundar"] || "",
    role: "ALL_ROUNDER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 60, runs: 378, wickets: 37, economy: 7.3, strikeRate: 116.3 },
    signatureSkill: "Tight Stumps-to-Stumps Powerplay Darts",
  },
  {
    id: "nitish-reddy",
    title: "Nitish Kumar Reddy",
    year: 21,
    genre: "Emerging Fast-Bowling All-Rounder",
    genres: ["All-Rounder", "Medium Pacer", "Emerging Player"],
    basePrice: 1.5,
    imdbRating: 9.1,
    boxOffice: 1200,
    director: "India",
    studio: "Emerging Player of the Year All-Rounder",
    category: "ALL_ROUNDERS",
    tagline: "Explosive pull shots, high strike rate, and handy seam bowling wickets",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["nitish-reddy"] || "",
    role: "ALL_ROUNDER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 15, runs: 303, wickets: 3, strikeRate: 142.9, highestScore: "76*" },
    signatureSkill: "Lofted On-Drive & Clever Change of Pace",
  },
  {
    id: "sam-curran",
    title: "Sam Curran",
    year: 26,
    genre: "Left-Arm Swing & Lower-Order Power",
    genres: ["All-Rounder", "Left-Arm Pacer", "T20 World Cup MVP"],
    basePrice: 2,
    imdbRating: 9.2,
    boxOffice: 2600,
    director: "England",
    studio: "T20 World Cup Player of the Tournament",
    category: "ALL_ROUNDERS",
    tagline: "Street-smart tactical competitor who delivers in crunch situations with bat and ball",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["sam-curran"] || "",
    role: "ALL_ROUNDER",
    country: "England",
    countryFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    stats: { matches: 59, runs: 883, wickets: 58, economy: 9.4, strikeRate: 135.2 },
    signatureSkill: "Bouncer to Right-Hander & Pinch-Hitting Blitz",
  },

  // ==========================================
  // --- SPIN WIZARDS (INDIAN & OVERSEAS) ---
  // ==========================================
  {
    id: "rashid-khan",
    title: "Rashid Khan",
    year: 26,
    genre: "World Premier Leg-Spinner & Finisher",
    genres: ["Bowler", "Spin Wizard", "Clutch Finisher"],
    basePrice: 2,
    imdbRating: 9.9,
    boxOffice: 150,
    director: "Afghanistan",
    studio: "Fast-Arm Googly Magician & Afghan King",
    category: "SPINNERS",
    tagline: "Rapid arm speed makes his lethal googly unreadable to world-class batters",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["rashid-khan"] || "",
    role: "SPIN_BOWLER",
    country: "Afghanistan",
    countryFlag: "🇦🇫",
    stats: { matches: 121, wickets: 149, economy: 6.8, strikeRate: 154.2, bestBowling: "4/24" },
    signatureSkill: "105 km/h Quick Googly & Snake Shot",
  },
  {
    id: "yuzvendra-chahal",
    title: "Yuzvendra Chahal",
    year: 34,
    genre: "All-Time Highest Wicket-Taker",
    genres: ["Bowler", "Leg-Spinner", "Chess Master"],
    basePrice: 2,
    imdbRating: 9.6,
    boxOffice: 205,
    director: "India",
    studio: "All-Time Historic Leading Wicket-Taker (205 Wickets)",
    category: "SPINNERS",
    tagline: "Brave tactical leg-spinner who lures batters into wide looping traps",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["yuzvendra-chahal"] || "",
    role: "SPIN_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 160, wickets: 205, economy: 7.8, bestBowling: "5/40" },
    signatureSkill: "Looping Wide Leg-Break & Hat-Trick Specialist",
  },
  {
    id: "kuldeep-yadav",
    title: "Kuldeep Yadav",
    year: 30,
    genre: "Left-Arm Wrist Spinner",
    genres: ["Bowler", "Wrist Spinner", "Mystery Turner"],
    basePrice: 1.5,
    imdbRating: 9.5,
    boxOffice: 86,
    director: "India",
    studio: "Chinaman Deception & Sharp Turn",
    category: "SPINNERS",
    tagline: "Sharp turn both ways off the surface with immense flight and dip",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["kuldeep-yadav"] || "",
    role: "SPIN_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 84, wickets: 87, economy: 7.9, bestBowling: "4/14" },
    signatureSkill: "Deceptive Drift & Big Sharp Wrong-Un",
  },
  {
    id: "varun-chakaravarthy",
    title: "Varun Chakaravarthy",
    year: 33,
    genre: "Mystery Carrom-Ball Architect",
    genres: ["Bowler", "Mystery Spinner", "Architect"],
    basePrice: 1.5,
    imdbRating: 9.3,
    boxOffice: 75,
    director: "India",
    studio: "Multi-Variation Mystery Strike Weapon",
    category: "SPINNERS",
    tagline: "Features 7 distinct variations including off-break, leg-break, carrom ball, and flipper",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["varun-chakaravarthy"] || "",
    role: "SPIN_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 71, wickets: 83, economy: 7.5, bestBowling: "5/20" },
    signatureSkill: "High-Trajectory Mystery Carrom Ball",
  },
  {
    id: "ravi-bishnoi",
    title: "Ravi Bishnoi",
    year: 24,
    genre: "Skiddy Quick Leg-Spinner",
    genres: ["Bowler", "Leg-Spinner", "Googly Specialist"],
    basePrice: 1.5,
    imdbRating: 9.2,
    boxOffice: 63,
    director: "India",
    studio: "Fast Skiddy Googly Nightmare",
    category: "SPINNERS",
    tagline: "Fires rapid googlies from a high release angle that rush batters off the pitch",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["ravi-bishnoi"] || "",
    role: "SPIN_BOWLER",
    country: "India",
    countryFlag: "🇮🇳",
    stats: { matches: 66, wickets: 63, economy: 7.9, bestBowling: "3/24" },
    signatureSkill: "100 km/h Arm Ball Googly & Acrobatic Fielding",
  },
  {
    id: "wanindu-hasaranga",
    title: "Wanindu Hasaranga",
    year: 27,
    genre: "Sri Lankan Leg-Spin Strike Bowler",
    genres: ["Bowler", "Spin Wizard", "All-Rounder"],
    basePrice: 2,
    imdbRating: 9.3,
    boxOffice: 35,
    director: "Sri Lanka",
    studio: "Purple Cap Contender & Googly Maestro",
    category: "SPINNERS",
    tagline: "Deceptive leg-breaks and unreadable googlies that clean-bowl middle-order anchors",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["wanindu-hasaranga"] || "",
    role: "SPIN_BOWLER",
    country: "Sri Lanka",
    countryFlag: "🇱🇰",
    stats: { matches: 26, wickets: 35, economy: 8.1, bestBowling: "5/18" },
    signatureSkill: "Rapid Sinking Googly",
  },
  {
    id: "noor-ahmad",
    title: "Noor Ahmad",
    year: 20,
    genre: "Left-Arm Afghan Mystery Spinner",
    genres: ["Bowler", "Wrist Spinner", "Mystery"],
    basePrice: 1.5,
    imdbRating: 9.0,
    boxOffice: 24,
    director: "Afghanistan",
    studio: "Teenage Afghan Chinaman Sensation",
    category: "SPINNERS",
    tagline: "Quick arm speed with sharp wrong-uns turning away from right-handers",
    photoUrl: CRICKETER_PORTRAIT_SEEDS["noor-ahmad"] || "",
    role: "SPIN_BOWLER",
    country: "Afghanistan",
    countryFlag: "🇦🇫",
    stats: { matches: 23, wickets: 24, economy: 7.9, bestBowling: "3/37" },
    signatureSkill: "Quick Turning Chinaman & Flipper",
  },
];

/**
 * Helper algorithm to compute the optimal Playing 11 from a squad of 12-18 players:
 * Enforces:
 * 1. Exactly 11 players (or all squad if < 11)
 * 2. Maximum 4 overseas players (0 to 4)
 * 3. At least 1 Wicketkeeper
 * 4. At least 3 Bowlers/All-Rounders
 * 5. Best player ratings and roles
 */
export function getOptimalPlaying11(squad: any[]): {
  playing11: string[];
  captainId?: string;
  viceCaptainId?: string;
} {
  if (!squad || squad.length === 0) return { playing11: [] };
  if (squad.length <= 11) {
    return {
      playing11: squad.map((p) => p.id),
      captainId: squad[0]?.id,
      viceCaptainId: squad[1]?.id,
    };
  }

  // Separate Indian vs Overseas
  const indianPlayers = squad.filter((p) => !isOverseasPlayer(p));
  const overseasPlayers = squad.filter((p) => isOverseasPlayer(p));

  // Sort by rating desc
  indianPlayers.sort((a, b) => (b.imdbRating || 9) - (a.imdbRating || 9));
  overseasPlayers.sort((a, b) => (b.imdbRating || 9) - (a.imdbRating || 9));

  // Select top max 4 overseas
  const pickedOverseas = overseasPlayers.slice(0, 4);
  const remainingNeeded = 11 - pickedOverseas.length;
  const pickedIndians = indianPlayers.slice(0, remainingNeeded);

  let selected = [...pickedOverseas, ...pickedIndians];

  // Guarantee at least 1 Wicketkeeper if available in the broader squad
  const hasKeeper = selected.some(
    (p) => p.role === "WICKETKEEPER" || p.genre?.includes("Keeper"),
  );
  if (!hasKeeper) {
    const keeperInSquad = squad.find(
      (p) => p.role === "WICKETKEEPER" || p.genre?.includes("Keeper"),
    );
    if (keeperInSquad && !selected.some((p) => p.id === keeperInSquad.id)) {
      const isKeeperOverseas = isOverseasPlayer(keeperInSquad);
      if (isKeeperOverseas) {
        // Replace lowest overseas
        if (pickedOverseas.length >= 4) {
          const lowestOverseas = pickedOverseas[pickedOverseas.length - 1];
          selected = selected.filter((p) => p.id !== lowestOverseas.id);
          selected.push(keeperInSquad);
        } else {
          // Replace lowest Indian
          const lowestIndian = selected.filter((p) => !isOverseasPlayer(p)).pop();
          if (lowestIndian) {
            selected = selected.filter((p) => p.id !== lowestIndian.id);
            selected.push(keeperInSquad);
          }
        }
      } else {
        // Replace lowest Indian
        const lowestIndian = selected.filter((p) => !isOverseasPlayer(p)).pop();
        if (lowestIndian) {
          selected = selected.filter((p) => p.id !== lowestIndian.id);
          selected.push(keeperInSquad);
        }
      }
    }
  }

  // Sort selected by role order (Batters -> Wicketkeepers -> All-Rounders -> Bowlers)
  const roleOrder: Record<string, number> = {
    BATTER: 1,
    WICKETKEEPER: 2,
    ALL_ROUNDER: 3,
    FAST_BOWLER: 4,
    SPIN_BOWLER: 5,
  };

  selected.sort((a, b) => {
    const rA = roleOrder[a.role] || 3;
    const rB = roleOrder[b.role] || 3;
    return rA - rB;
  });

  const bestPlayer = [...selected].sort((a, b) => (b.imdbRating || 9) - (a.imdbRating || 9))[0];
  const secondBest = [...selected].sort((a, b) => (b.imdbRating || 9) - (a.imdbRating || 9))[1];

  return {
    playing11: selected.map((p) => p.id),
    captainId: bestPlayer?.id,
    viceCaptainId: secondBest?.id,
  };
}

export function getRandomizedCricketSlate(
  count = 60,
  category = "ALL",
): CricketPlayerItem[] {
  let basePool = [...cricketPlayers];

  if (category && category !== "ALL") {
    const matching = basePool.filter((p) => p.category === category || p.role === category);
    if (matching.length >= count) {
      basePool = matching;
    } else if (matching.length > 0) {
      const matchIds = new Set(matching.map((p) => p.id));
      const rest = basePool.filter((p) => !matchIds.has(p.id));
      basePool = [...matching, ...rest];
    }
  }

  // Fisher-Yates shuffle
  const pool = [...basePool];
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    const temp = pool[i]!;
    pool[i] = pool[j]!;
    pool[j] = temp;
  }

  if (count <= pool.length) {
    return pool.slice(0, count);
  }

  // If count requested exceeds base pool (e.g. 60, 85, 110, 135, 160), generate uniquely indexed players
  const extendedList: CricketPlayerItem[] = [...pool];
  let cycle = 1;
  while (extendedList.length < count) {
    for (const item of pool) {
      if (extendedList.length >= count) break;
      extendedList.push({
        ...item,
        id: `${item.id}-draft-${cycle}`,
        title: `${item.title}`,
      });
    }
    cycle++;
  }

  return extendedList.slice(0, count);
}
