/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GameRoomCodeRouteImport } from './routes/game.$roomCode'
import { Route as ResultsRoomCodeRouteImport } from './routes/results.$roomCode'
import { Route as RoomRoomCodeRouteImport } from './routes/room.$roomCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoomCodeRoute = GameRoomCodeRouteImport.update({
  id: '/game/$roomCode',
  path: '/game/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoomCodeRoute = ResultsRoomCodeRouteImport.update({
  id: '/results/$roomCode',
  path: '/results/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomCodeRoute = RoomRoomCodeRouteImport.update({
  id: '/room/$roomCode',
  path: '/room/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/game/$roomCode': typeof GameRoomCodeRoute
  '/results/$roomCode': typeof ResultsRoomCodeRoute
  '/room/$roomCode': typeof RoomRoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/game/$roomCode': typeof GameRoomCodeRoute
  '/results/$roomCode': typeof ResultsRoomCodeRoute
  '/room/$roomCode': typeof RoomRoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/join': typeof JoinRoute
  '/game/$roomCode': typeof GameRoomCodeRoute
  '/results/$roomCode': typeof ResultsRoomCodeRoute
  '/room/$roomCode': typeof RoomRoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/join'
    | '/game/$roomCode'
    | '/results/$roomCode'
    | '/room/$roomCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/join'
    | '/game/$roomCode'
    | '/results/$roomCode'
    | '/room/$roomCode'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/join'
    | '/game/$roomCode'
    | '/results/$roomCode'
    | '/room/$roomCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  JoinRoute: typeof JoinRoute
  GameRoomCodeRoute: typeof GameRoomCodeRoute
  ResultsRoomCodeRoute: typeof ResultsRoomCodeRoute
  RoomRoomCodeRoute: typeof RoomRoomCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$roomCode': {
      id: '/game/$roomCode'
      path: '/game/$roomCode'
      fullPath: '/game/$roomCode'
      preLoaderRoute: typeof GameRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$roomCode': {
      id: '/results/$roomCode'
      path: '/results/$roomCode'
      fullPath: '/results/$roomCode'
      preLoaderRoute: typeof ResultsRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomCode': {
      id: '/room/$roomCode'
      path: '/room/$roomCode'
      fullPath: '/room/$roomCode'
      preLoaderRoute: typeof RoomRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  JoinRoute: JoinRoute,
  GameRoomCodeRoute: GameRoomCodeRoute,
  ResultsRoomCodeRoute: ResultsRoomCodeRoute,
  RoomRoomCodeRoute: RoomRoomCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
